name: mineral_contract
description: Develop your own packages thanks to this base offering you access to Mineral's core contracts
version: 1.5.1

repository: https://github.com/mineral-dart/package
# homepage: https://www.example.com

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  collection: ^1.17.1
  mineral_ioc: ^2.0.0
  path: ^1.8.0
  yaml: ^3.1.1
